[package]
name = "hubless"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
async-trait = "0.1.77"
axum = "0.7.4"
russh = "0.40.2"
russh-keys = "0.40.1"
serde_json = "1.0.1"
tokio = { version = "1.35.1", features = ["full"] }
